// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJN-VmBfBaWz2o8cVKYn2qMYCeR-wW0M4',
    appId: '1:378841280424:web:ae563acc03fc68007ff79d',
    messagingSenderId: '378841280424',
    projectId: 'movie-app-30945',
    authDomain: 'movie-app-30945.firebaseapp.com',
    storageBucket: 'movie-app-30945.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDabv2pZRourIGt1I5s-b_V1ZGFjsmR2wc',
    appId: '1:378841280424:android:7094c2d3e9baf1a77ff79d',
    messagingSenderId: '378841280424',
    projectId: 'movie-app-30945',
    storageBucket: 'movie-app-30945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF79phT0jNIOfn0fn5esduNRgaolsq-sE',
    appId: '1:378841280424:ios:f8ba0d56956e3d837ff79d',
    messagingSenderId: '378841280424',
    projectId: 'movie-app-30945',
    storageBucket: 'movie-app-30945.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJN-VmBfBaWz2o8cVKYn2qMYCeR-wW0M4',
    appId: '1:378841280424:web:5c1a87ec681f4cf07ff79d',
    messagingSenderId: '378841280424',
    projectId: 'movie-app-30945',
    authDomain: 'movie-app-30945.firebaseapp.com',
    storageBucket: 'movie-app-30945.firebasestorage.app',
  );
}
